version: '2'

services:
  mysql:
    image: mysql
    container_name: product-catalog-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "productCatalogDB"
    volumes:
      - ./database/docker-mysql:/var/lib/mysql
